# Rename the project and update the description for your project
name: rvpodhooks
description: "Flutter template with Riverpod Hooks, GoRouter and
  ResponsiveFramework (Clean Architecture)"
publish_to: "none"
version: 0.1.0

# Update the SDK version to the latest stable version
environment:
  sdk: ">=3.3.4 <4.0.0"

# Core Dependencies: (add/update using pubspec assist)
#
# hooks_riverpod,flutter_hooks,go_router,responsive_framework,intl,animations,json_annotation,freezed_annotation,http,shared_preferences,flutter_svg,vector_graphics
#
dependencies:
  animations: ^2.0.11
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^14.0.2
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  responsive_framework: ^1.4.0
  shared_preferences: ^2.2.3
  vector_graphics: ^1.1.11+1

# Core Dev Dependencies: (add/update using pubspec assist)
#
# build_runner,custom_lint,flutter_lints,freezed,json_serializable,riverpod_lint
#
dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.10

# Assets and Fonts
# Modify the assets and fonts section to match your project's assets and fonts
#
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
